"""new fields in user model

Revision ID: 131805ce6890
Revises: c346f90e45e0
Create Date: 2019-02-18 23:37:28.380869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '131805ce6890'
down_revision = 'c346f90e45e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
